Repository iamgio/quarkdown, pull requests merged in 2025-09, with the labels that each got.

#188 perf!: optimize live preview
  quarkdown-cli/src/main/kotlin/com/quarkdown/cli/exec/CompileCommand.kt
  quarkdown-cli/src/main/kotlin/com/quarkdown/cli/exec/Execute.kt
  quarkdown-cli/src/main/kotlin/com/quarkdown/cli/exec/ExecuteCommand.kt
  quarkdown-cli/src/main/kotlin/com/quarkdown/cli/server/StartWebServerCommand.kt
  quarkdown-cli/src/main/kotlin/com/quarkdown/cli/server/WebServerOptions.kt
  quarkdown-cli/src/main/kotlin/com/quarkdown/cli/server/WebServerStarter.kt
  quarkdown-cli/src/main/kotlin/com/quarkdown/cli/watcher/DirectoryWatcher.kt
  quarkdown-core/src/main/kotlin/com/quarkdown/core/rendering/template/TemplatePlaceholders.kt
  quarkdown-html/src/main/kotlin/com/quarkdown/rendering/html/post/HtmlPostRenderer.kt
  quarkdown-html/src/main/kotlin/com/quarkdown/rendering/html/post/HtmlPostRendererTemplate.kt
  quarkdown-html/src/main/resources/render/html-wrapper.html.template
  quarkdown-html/src/main/resources/render/script/paged.js
  quarkdown-html/src/main/resources/render/script/script.js
  quarkdown-html/src/main/resources/render/script/websockets.js
  quarkdown-server/README.md
  quarkdown-server/build.gradle.kts
  quarkdown-server/src/main/kotlin/com/quarkdown/server/LocalFileWebServer.kt
  quarkdown-server/src/main/kotlin/com/quarkdown/server/Server.kt
  quarkdown-server/src/main/kotlin/com/quarkdown/server/ServerEndpoints.kt
  quarkdown-server/src/main/kotlin/com/quarkdown/server/browser/BrowserLauncher.kt
  quarkdown-server/src/main/kotlin/com/quarkdown/server/endpoints/LivePreviewEndpoint.kt
  quarkdown-server/src/main/kotlin/com/quarkdown/server/endpoints/ReloadEndpoint.kt
  quarkdown-server/src/main/kotlin/com/quarkdown/server/message/ServerMessage.kt
  quarkdown-server/src/main/kotlin/com/quarkdown/server/message/ServerMessageSession.kt
  quarkdown-server/src/main/kotlin/com/quarkdown/server/message/ServerMessageType.kt
  quarkdown-server/src/main/resources/live-preview/wrapper.html.template
  quarkdown-server/src/test/kotlin/com/quarkdown/server/LocalFileWebServerTest.kt
  quarkdown-server/src/test/resources/test.html
Labels: performance

#196 fix(code): fix line numbers and first-line indentation of code blocks spanning across different pages
  quarkdown-html/src/main/resources/render/script/paged.js
  quarkdown-html/src/test/resources/issues/split-code-block.qd
Labels: bug

#201 fix(live-preview): fix live preview refreshing to the wrong slide in slides documents
  quarkdown-server/src/main/resources/live-preview/wrapper.html.template
Labels: bug

#204 feat: add french translations
  quarkdown-libs/src/main/resources/paper.qd
  quarkdown-stdlib/src/main/resources/lib/localization.qd
Labels: localization
